import("//build_overrides/build.gni")

static_library("compile_smoketest_lib") {
  sources = [ "smoketest.cc" ]

  # No explicit libc++ dependency, use system default.
  deps = []
}

source_set("compile_smoketest_gurl") {
  sources = [ "smoketest_gurl.cc" ]
  deps = [ "//third_party/googleurl" ]
}

source_set("compile_smoketest_platform") {
  sources = [ "smoketest_platform.cc" ]
  deps = [ "//platform:base" ]
}

source_set("compile_smoketest_gtest") {
  testonly = true
  sources = [ "smoketest_unittest.cc" ]
  deps = [
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

executable("compile_smoketest_logging_win_unittest") {
  testonly = true
  sources = [ "logging_win_unittest.cc" ]
  deps = [
    "//platform:api",
    "//platform:standalone_impl",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

group("compile_smoketest") {
  testonly = true
  deps = [
    ":compile_smoketest_gtest",
    ":compile_smoketest_gurl",
    ":compile_smoketest_lib",
    ":compile_smoketest_logging_win_unittest",
    ":compile_smoketest_network_interface_win_unittest",
    ":compile_smoketest_platform",
    ":compile_smoketest_task_runner_win_unittest",
    ":compile_smoketest_time_unittest",
    ":compile_smoketest_quiche",
  ]
}

executable("compile_smoketest_udp_socket_win_unittest") {
  testonly = true
  sources = [ "udp_socket_win_unittest.cc" ]
  deps = [
    "//platform:api",
    "//platform:standalone_impl",
    "//platform:test",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

executable("compile_smoketest_network_interface_win_unittest") {
  testonly = true
  sources = [ "network_interface_win_unittest.cc" ]
  deps = [
    "//platform:api",
    "//platform:standalone_impl",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

executable("compile_smoketest_task_runner_win_unittest") {
  testonly = true
  sources = [ "task_runner_win_unittest.cc" ]
  deps = [
    "//platform:api",
    "//platform:standalone_impl",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

executable("compile_smoketest_time_unittest") {
  testonly = true
  sources = [ "time_unittest.cc" ]
  deps = [
    "//platform:api",
    "//platform:standalone_impl",
    "//third_party/googletest:gtest",
    "//third_party/googletest:gtest_main",
  ]
  configs -= [ "//build/config/clang:find_bad_constructs" ]
}

source_set("compile_smoketest_quiche") {
  sources = [ "quiche_smoketest.cc" ]
  deps = [ "//third_party/quiche" ]
}
